name: Go test workflow
on: [push]
#
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18.x', '1.19.x' ]
    #
    steps:
      - uses: actions/checkout@v3
      #- shell: bash
      #  name: Add FFmpeg to PATH
      #  run: |
      #    sudo add-apt-repository ppa:savoury1/ffmpeg4
      #    sudo add-apt-repository ppa:savoury1/ffmpeg5
      #    sudo apt-get -y update
      #    sudo apt-get -y upgrade && sudo apt-get dist-upgrade
      #    sudo apt-get -y install ffmpeg
      #
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      #- run: ffmpeg -i asset/input.mp4 output.mp4
      #
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          #cache: true
      #
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      #
      #- name: Install dependencies
      #  run: go get .
      #
      - name: Build
        run: go build -v ./... 
      #
      - name: Test with the Go CLI
        run: go test -v ./...
      #
    #
  #
#